steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/smallweb:${SHORT_SHA}', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/smallweb:${SHORT_SHA}']
  - name: google/cloud-sdk
    args: [
      'gcloud',
      'run',
      'deploy',
      'smallweb',
      '--image=us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/smallweb:${SHORT_SHA}',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--set-env-vars', 'URL_PREFIX=/smallweb',
      '--service-account', 'smallweb@${PROJECT_ID}.iam.gserviceaccount.com',
      '--cpu=2',
      '--memory=2Gi',
      '--min-instances', '1',
      # NOTE(Luan): Smallweb seems to have an issue with running more than 1
      # instance, let's keep it as max = 1
      '--max-instances', '1'
    ]
images:
  - us-central1-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY_REPO}/smallweb:${SHORT_SHA}
